M48
; DRILL file {KiCad 9.0.7} date 2026-05-16T18:23:08-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-16T18:23:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X1.8276Y-2.5839
X1.8276Y-2.8115
T2
X1.6515Y-1.8449
X1.6915Y-2.0449
X1.7315Y-1.8449
M30
